compasjs/compas

packages/lint-config/index.js
For more information see https://eslint.org/docs/rules/no-unsafe-optional-chaining
=> lint-config: add no-unsafe-optional-chain rule to lint config

gen/code-gen.js, packages/code-gen/index.d.ts, packages/code-gen/src/App.js, packages/code-gen/src/generate.js, packages/code-gen/src/generated/anonymous-validators.js, packages/code-gen/src/generated/types.js, packages/code-gen/src/generated/validators.js, packages/code-gen/src/generator/errors.js, packages/code-gen/src/generator/router/index.js, packages/code-gen/src/generator/router/templates/routerFile.tmpl, packages/code-gen/src/generator/sql/utils.js, packages/code-gen/src/generator/structure.js, packages/code-gen/src/generator/validator.js, scripts/internal_generate.js
We only want to exposes the necessary things outside of the api. This is only the router and related types. This can now be enabled via `dumpApiStructure`.
This also results in `dumpStructure` never being enabled by default, and is thus manually needed when creating packages.
This also adds a `throwingValidators` option. This is expected by the router and sql generator. However it is only enabled by default with `isNodeServer`.
Closes #525
=> code-gen: add dumpApiStructure and throwingValidators options

packages/insight/src/logger/logger.js, packages/stdlib/src/env.js, packages/stdlib/src/env.test.js
We now by default run in 'production'-mode, except when `NODE_ENV=development` is passed in explicitly. This should make the default more secure.
=> insight,stdlib: stricter NODE_ENV checks

packages/cli/scripts/test.js, packages/cli/src/cli.js, packages/cli/src/commands/bench.js, packages/cli/src/commands/coverage.js, packages/cli/src/commands/test.js, packages/cli/src/parse.js, packages/cli/src/parse.test.js, packages/cli/src/testing/config.js, packages/cli/src/testing/printer.js, packages/cli/src/testing/state.js, packages/cli/src/testing/test.js, packages/cli/src/testing/utils.js, packages/cli/src/utils.js, packages/stdlib/src/utils.test.js, test/config.js, test/repo/migrations.test.js
The test runner now uses worker_threads to dispatch test files. Every worker runs the global setup before executing tests and runs the global teardown when no test files are available.
The unit of distribution used are files, so tests in a single file will always run in serial.
When `--serial` is passed, the standard test runner is used, and the same happens when you execute a test file directly and call `mainTestFn`.
To find flaky tests you can use `--randomize-rounds=n`, where n is any integer. This will randomize the files passed to workers. Note that the workers are restarted after every full test run, and thus the global setup and teardown are execute multiple times.
To enable these arguments, the cli parser also got upgraded. We try to match Node.js arguments against their long …
=> cli: add parallel test running and order randomizer

packages/store/src/queue.js
This ensures that high prio jobs will be picked up first even if low prio jobs are scheduled first.
In the old scenario, earlier scheduled jobs will always have priority over higher priority jobs.
Closes #597
=> store: prioritize priority over scheduled at in JobWorker

packages/stdlib/src/datatypes.js
The crypto.randomUUID function is added in Node.js v15.6.0. It is about 30 percent faster than the vendored version.
=> stdlib: use crypto randomUUID if available

packages/stdlib/src/utils.js
This way it is more clear why the process exits, for example for a 'unhandledRejection'.
Closes #625
=> stdlib: add types to process errors

packages/store/src/generated.js
This may prevent some soft delete bugs. We don't handle the errors thrown if queries is not set, so we should document this!
=> store: force call `setStoreQueries`

packages/code-gen/src/generator/sql/query-builder.js, packages/code-gen/test/sql.test.js, packages/store/src/generated/database/file.js, packages/store/src/generated/database/fileGroup.js, packages/store/src/generated/database/fileGroupView.js, packages/store/src/generated/database/index.js, packages/store/src/generated/database/job.js, packages/store/src/generated/database/session.js
This may prevent some errors, and improves on th readability of existing errors when doing `const [foo] = await queryFoo();`
=> code-gen: throw when generated queryBuilder function is awaited

.github/workflows/create-release.yml, scripts/create-release.js
When a commit on 'main' contains the words 'prepare' and 'release' this job should run. It will get the new version out of the latest commit message and execute Lerna.
After that we expect Lerna to have pushed some tags and fill in the Github release with the changelog for that version.
=> ci: automate release process

packages/code-gen/src/builders/OmitType.js, packages/code-gen/src/builders/OptionalType.js, packages/code-gen/src/builders/PickType.js, packages/code-gen/src/builders/SearchableType.js
A pretty long unnoticed bug for Compas standards, oh well.
Closes #637
=> code-gen: fix names for optional, pick, omit and searchable type

packages/code-gen/src/generator/sql/partial-type.js, packages/store/src/generated/types.js
=> code-gen: fix field types of update partial for optional fields

packages/store/index.d.ts, packages/store/index.js, packages/store/src/query.js, packages/store/src/query.test.js
Helps with debugging queries or when you quickly want to see what query is generated. Supports a bit of interpolating variables, but may not work in a lot of cases. Haven't decided yet if I want to harden the implementation or remove it. But we'll roll with it for now
Closes #644
=> store: add stringifyQueryPart function

.eslintignore, packages/code-gen/src/generator/validator.js, packages/code-gen/test/e2e-server.test.js, packages/store/src/generated/validators.js
We can now validate files in a few places where we previously we could only check if it was available:
- `isBrowser` api input
- `isBrowser` api output
- `!isBrowser` api client input
- `!isBrowser` api response
- `!isBrowser` route validators via router
Closes #645
=> code-gen: add file validator support

packages/server/src/testing.js
=> server: catch errors while creating and closing a test app

packages/code-gen/src/generator/sql/query-builder.js, packages/code-gen/src/generator/sql/structure.js, packages/code-gen/test/sql.test.js, packages/store/src/generated/database/file.js, packages/store/src/generated/database/fileGroup.js, packages/store/src/generated/database/fileGroupView.js
This works by intersecting the result of multiple traverses. This guarantees the same 'AND' behaviour as usual. It also works when the 'xxIn' property is already set, by converting it inline to a 'select from values' expression.
Closes #660
=> code-gen: support multiple 'viaXxx' in the query builder

packages/store/index.d.ts, packages/store/src/queue.js, packages/store/src/queue.test.js
Add the option to add a handlerTimeout on Queue worker creation. This defaults to 30 seconds. A faster timeout increases throughput and may force for smaller targeted jobs instead of doing all kinds of things in a single job. Combined with the retry count, this should prevent the worker from ever getting stuck on jobs that can't be completed.
Closes #651
=> feat(store): handler timeout for job queue

packages/stdlib/src/node.js, scripts/linkExternally.js, scripts/syncMetadata.js
=> fix(stdlib): force use of posix path join

packages/store/index.d.ts, packages/store/src/queue.js, packages/store/src/queue.test.js
This is a breaking change.
We now construct a fresh logger and corresponding event, to pass to the JobQueueWorker handler. This allows us to print call stacks, add a default logger and more.
Closes #674
=> feat(store): add event to queue worker handler

packages/stdlib/src/node.js, packages/store/src/file-cache.js
Just make the code a bit easier to reason about.
=> feat(stdlib): remove pipeline from streamToBuffer

packages/code-gen/src/generator/sql/query-builder.js, packages/store/src/generated/database/file.js, packages/store/src/generated/database/fileGroup.js, packages/store/src/generated/database/fileGroupView.js
The relation type (oneToMany, ManyToOne) was missing for the secondary query builder. This resulted in some `null` values instead of empty array's (`[]`), because of some missing `coalesce` calls.
This is resolved and regenerated for the store package
=> fix(code-gen): fix missing relation type in sub query builder

packages/code-gen/src/generator/reactQuery/templates/reactQueryFile.tmpl, packages/code-gen/src/generator/reactQuery/templates/reactQueryFn.tmpl
This allows reactQuery consumers to for example invalidate a query without having to know the internal query keys.
This allows us to do some improvements to the generated keys, without doing breaking changes to the user.
References #697
=> feat(code-gen): expose query key functions for generated hooks

gen/testing.js, packages/code-gen/src/generator/validator.js, packages/code-gen/test/validators.test.js, packages/store/src/generated/anonymous-validators.js
The Date validator now passes `isOptional` and `allowNull` values down to the string validator. So dates can be set to `null` or `undefined` if an empty string is passed in.
Closes #551
=> fix(code-gen): date validator should support special string cases

packages/code-gen/src/generator/reactQuery/templates/reactQueryFn.tmpl
This allows operations on queries with less exact predicates. This is useful, for example, when the exact query parameters aren't directly accessible inside components.
E.g.
```
queryClient.invalidateQueries([useSellerSignupOrderSummary.baseKey]);
```
See https://react-query.tanstack.com/guides/query-invalidation for more examples
=> feat(code-gen): expose baseKeys for generated hooks

packages/cli/scripts/lint.js, packages/cli/src/commands/lint.js, packages/lint-config/index.js
This enables the JSDoc ESLint rules
=> feat(cli): support `--jsdoc` flag on `compas lint`

packages/code-gen/src/generator/sql/where-type.js, packages/code-gen/test/sql.test.js, packages/store/src/generated/database/file.js, packages/store/src/generated/database/fileGroup.js, packages/store/src/generated/database/fileGroupView.js, packages/store/src/generated/database/job.js, packages/store/src/generated/database/session.js
For some reason we skipped over empty `xxIn` arrays in the where generator. Now we handle the empty case correctly.
=> fix(code-gen): fix empty where xxIn behaviour in the sql generator

packages/cli/src/benchmarking/runner.js, packages/lint-config/index.js, packages/lint-config/package.json, yarn.lock
Babel-eslint is deprecated for a long time, but we use some stage 3 proposals in Node.js that are not yet supported by the default ESLint parser
Closes #744
=> feat(lint-config): move to @babel/eslint-parser

packages/cli/scripts/test.js, packages/cli/src/commands/proxy.js, packages/cli/src/execute.js, packages/cli/src/utils.js, packages/code-gen/src/generator/index.js, packages/code-gen/src/generator/sql/query-basics.js, packages/code-gen/src/generator/sql/query-builder.js, packages/insight/src/postgres.test.js, packages/lint-config/index.js, packages/server/src/app.test.js, packages/server/src/middleware/compose.test.js, packages/server/src/middleware/log.js, packages/server/src/middleware/session.test.js, packages/stdlib/src/node.js, packages/store/src/file-cache.test.js, packages/store/src/file-group.js, packages/store/src/files.js, packages/store/src/generated/database/file.js, packages/store/src/generated/database/fileGroup.js, packages/store/src/generated/database/fileGroupView.js, packages/store/src/generated/database/job.js, packages/store/src/generated/database/session.js, packages/store/src/migrations.js, packages/store/src/minio.js, packages/store/src/query.js, packages/store/src/queue.test.js, packages/store/src/sessions.test.js
There is no built-in rule or rule plugin that adds more of these best practices. So follow this one for now.
This should improve the stacktrace in async scenarios
Closes #751
=> feat(lint-config): remove no-return-await add require-await

packages/code-gen/src/generator/apiClient/templates/apiClientFile.tmpl, packages/code-gen/src/generator/apiClient/templates/apiClientFn.tmpl, packages/code-gen/src/generator/reactQuery/templates/reactQueryFile.tmpl, packages/code-gen/src/generator/reactQuery/templates/reactQueryFn.tmpl, packages/code-gen/test/e2e-server.test.js, packages/server/src/app.test.js
This is a breaking change. The `useApi` hook now stores an axios instance instead of the api client object. This also removes some of the 'isBrowser' checks that we had in here.
The generated react-query hooks also import the specific api functions, so pages should only include the api calls that they use in the bundles.
Closes #730
=> feat(code-gen): generate a code splittable api client

packages/cli/scripts/lint.js
=> fix(cli): prevent ESLint from throwing errors when no JS files are found

packages/code-gen/src/generator/router/index.js, packages/code-gen/src/generator/router/templates/routerFile.tmpl, packages/code-gen/src/generator/router/trie.js
By postfix the request method instead of prefixing, a lot of branching happens at the root, based on defined routes names, instead of nested per method.
This gives a 10 to 40 percent performance improvement, depending on the amount of routes registered.
/cc @tjonger
=> feat(code-gen): improve generated router performance

packages/code-gen/src/generator/sql/query-builder.js, packages/code-gen/test/sql.test.js, packages/store/src/generated/database/file.js, packages/store/src/generated/database/fileGroup.js, packages/store/src/generated/database/fileGroupView.js
When a 'via' is used, whe automatically transform the existing 'idIn' array so we can use it in a 'INTERSECT' query, to give the 'AND' guarantee. This was not tested propertly with multiple values in the 'idIn' array
References #886
=> fix(code-gen): transformation for idIn and via combination

packages/stdlib/src/utils.js
This is abused by the test runner in serial mode. Let's take another look later
=> fix(stdlib): revert mainFn only running once check

packages/code-gen/src/generator/sql/query-builder.js, packages/store/src/generated/database/fileGroup.js, packages/store/src/generated/database/fileGroupView.js
Using the array constructor instead of array_remove(array_agg())
Same performance on simple queries, 10 percent improvement for nested aggregates
=> perf(code-gen): improve generated query builder performance

packages/cli/src/commands/visualise.test.js, packages/cli/src/migrate/migrate.test.js, packages/cli/src/testing/config.js, packages/cli/src/testing/runner.js, packages/cli/src/testing/state.js, packages/cli/src/testing/state.test.js, packages/cli/src/utils.test.js, packages/code-gen/test/e2e-server.test.js, packages/code-gen/test/sql.test.js, packages/server/src/middleware/body.test.js, packages/server/src/middleware/compose.test.js, packages/server/src/middleware/session.test.js, packages/stdlib/src/utils.test.js, packages/store/src/file-cache.test.js, packages/store/src/file-group.test.js, packages/store/src/files.test.js, packages/store/src/minio.test.js, packages/store/src/postgres.test.js, packages/store/src/query.test.js, packages/store/src/queue.test.js, test/config.js
Configurable via test/config.js by exporting a constant boolean 'enforceSingleAssertion'. This is enforced when a `test` or `t.test` does not have any children via `t.test` and also does no assertions. And will result in the same handling as caught exceptions. It defaults currently to 'false', but may be switched to 'true' later.
This changes try / catch testing a bit from:
```js
test("err", t => {
try {
shouldThrow();
t.fail("Should throw");
} catch (e) {
// Assert on 'e' or ignore
}
});
```
to:
```js
test("err", t => {
try {
shouldThrow();
} catch (e) {
// Assert on 'e' or
t.pass();
}
});
```
Closes #820
=> feat(cli): add option to enforce at least one test assertion

packages/code-gen/src/generator/common.js, packages/code-gen/src/generator/reactQuery/templates/reactQueryFn.tmpl
Adds the third generic support to `useQueryOptions` and removes the `UseQueryResult` casting as it should get automatically inferred based on the return type and `useQueryOptions`
This will allow for correctly inferring data when the selector option is used
```javascript
// Data correctly inferred as data type
const { data } = useSomeQuery()
// Data correctly inferred as someOtherValue type
const { data } = useSomeQuery({ select: (data) => data.someOtherValue })
```
=> feat(code-gen): add additional query generics to react query codgen

packages/code-gen/src/generator/router/templates/routerFile.tmpl, packages/code-gen/test/e2e-server.test.js
This allows to overwrite the handlers at runtime, when requests did already hit the old handler. This clears the cache for all handlers synchronously, and may give a performance penalty for the first few calls for that handler.
Closes #958
=> feat(code-gen): add 'routerClearMemoizedHandlers' to router output

packages/store/src/postgres.js
This PR will enable SSL for connections.
For production environments it will be required, and elsewhere it's preferred.
=> fix(store): require ssl by default for the postgres connection in production

gen/testing.js, packages/code-gen/src/generator/types.js
before:
```ts
export type ServerAnswers = { [ key: ServerOptions]:string};
export type ServerOptions = "A"|"B"|"C";
```
after:
```ts
export type ServerAnswers = { [ K in ServerOptions]:string};
export type ServerOptions = "A"|"B"|"C";
```
=> fix(code-gen): resolve typescript union on compas reference object

packages/stdlib/index.d.ts, packages/stdlib/src/events.js, packages/stdlib/src/events.test.js
The duration is added to the 'start' object in the callStack.
Closes #979
=> feat(stdlib): calculate event duration on abort or eventStop

gen/testing.js, packages/code-gen/src/generator/reactQuery/templates/reactQueryFn.tmpl
Fixed quoting in a path that was never hit previously
Closes #991
=> fix(code-gen): react-query should work for routes without a response

packages/cli/scripts/test.js, packages/cli/src/commands/help.js, packages/cli/test/command-test.test.js
Usable in high core count machines.
Closes #993
=> feat(cli): support `--parallel-count n` in the test runner

packages/store/src/file-cache.js
We use a low max age since files may change relatively fast if a job picks it up. By adding `must-revalidate` we hope that the browser tries to use `if-modified-since`, and thus skips the complete content download.
- The default has changed from `max-age=1200` to `max-age=120, must-revalidate`. Provide your own as the last argument of `new FileCache()` if necessary.
=> feat(store): add must-revalidate to default cacheControlHeader

packages/code-gen/src/generator/router/templates/routerFile.tmpl
This way it's obvious which event is which, when the executed function has the same event name
=> feat(code-gen): rename `ctx.event` in matched handlers with a `router.` prefix

packages/cli/scripts/test.js, packages/cli/src/commands/coverage.js, packages/cli/src/commands/help.js
Closes #1022
- `compas coverage` by defaults executes tests with the default settings (parallel)
- `compas coverage` now also accepts all arguments of `compas test` like `--serial` and `--parallel-count`. To get the old behaviour run `compas coverage --serial`
=> feat(cli): run tests in parallel by default while collecting coverage

packages/cli/index.d.ts, packages/cli/src/testing/events.js
Closes #1030
- Removed the `options` argument on `newTestEvent`. This was more confusing than a few extra logs in the test output.
=> feat(cli): remove `newTestEvent` options

.gitignore, packages/code-gen/src/App.js, packages/code-gen/src/generator/errors.test.js, packages/code-gen/src/generator/index.js, packages/code-gen/src/generator/sql/add-fields.js, packages/code-gen/test/utils.test.js
Also fixes some minor issues with `isNode` being to greedy, and supporting the case that no generator is enabled.
Closes #1021
=> test(code-gen): add e2e tests for handled errors

packages/code-gen/src/generator/sql/query-basics.js, packages/code-gen/test/sql.test.js, packages/store/src/generated/database/file.js, packages/store/src/generated/database/fileGroup.js, packages/store/src/generated/database/job.js, packages/store/src/generated/database/session.js, packages/store/src/testing.js
- The primary key & createdAt fields are skipped when upserting
- Optional values from the existing row are kept, even if the provided insert values have an explicit null value.
Closes #1080
=> feat(code-gen): add sql upsert on primary key support

__fixtures__/store/996-js-migration.js, __fixtures__/store/997-test.sql, packages/store/src/migrations.js, packages/store/src/migrations.test.js
By exporting a migrate function, the users have more flexibility to do some business / conditional logic based on for example env values.
Closes #1092
=> feat(store): add support for JS migration files

packages/store/src/files.js
Transformed artifacts generated via for example `sendTransformedImage` are now permanently deleted if the original is removed.
=> fix(store): syncDeletedFiles permanently delete transformed

packages/code-gen/src/stringify.js, packages/store/src/generated/common/anonymous-validators.d.ts, packages/store/src/generated/common/anonymous-validators.js
The validator generator creates hashes of types to deduplicate anonymous validator functions. The deduper didn't account for custom validator & type imports for the any type, which meant that the first `T.any()` processed by the validator would be used for all places that `T.any()` was used, even if it had something like `T.any().validator("isQueryPart", { javaScript: "@compas/store", typeScript: "@compas/store")`.
=> fix(code-gen): correct reuse of any validators

packages/cli/src/commands/visualise.js, packages/cli/src/commands/visualise.test.js
Graphviz / Dot does not create the output directory if it doesn't exists. So make sure to do that before spawning dot.
Closes #1206
=> fix(cli): ensure visualise output directory exists

packages/cli/src/commands/visualise.js, packages/store/src/queue.d.ts, packages/store/src/queue.js, packages/store/src/queue.test.js
Added `includedNames` & `excludedNames` options. Only one can be specified.
The `pendingQueueSize() & averageTimeToCompletion()` methods on the `JobQueueWorker` also respect these filters.
Closes #1223
- Removed support for specifying a specific job name in the `JobQueueWorker` constructor. Please migrate to the `{ includedNames: ["job.name"] }` syntax.
=> feat(store): add job name filter to JobQueueWorker

packages/cli/src/commands/proxy.js, packages/code-gen/src/generator/common.js, packages/code-gen/test/e2e-server.test.js, packages/server/src/app.test.js, packages/server/src/middleware/cors.js, packages/server/src/middleware/log.js
The existing behaviour was to try to propagate the request id over requests, but that didn't work with requests happening from server side rendering. And it's also not privacy-friendly.
So now we use a requestId in the backend to find request related logs, and nothing more.
- Removed `addRequestIdInterceptors` from `$generatedDir/common/apiClient`
=> feat(code-gen,server): change requestId behaviour

packages/server/src/app.js, packages/server/src/middleware/log.d.ts, packages/server/src/middleware/log.js
These are emitted if for example the socket is hang up from the browser.
It tries to use the request logger but else uses a 'http-error' context type logger.
=> feat(server): log middleware also handles Koa error events

packages/code-gen/src/generated/common/anonymous-validators.d.ts, packages/code-gen/src/generated/common/anonymous-validators.js, packages/code-gen/src/generator/validator.js, packages/code-gen/test/validators.test.js, packages/store/src/generated/common/anonymous-validators.d.ts, packages/store/src/generated/common/anonymous-validators.js
Now allows any valid number or string that is accepted by the date constructor, since for some cases the full timestamp may be too strict.
Closes #1229
=> feat(code-gen): make date validator more flexible

packages/code-gen/src/generator/types.js, packages/code-gen/src/generator/validator.js, packages/server/package.json, yarn.lock
Closes #1317
- Renamed properties on `ctx.validatedFiles`.
- `ctx.validatedFiles.xxx.path` -> `ctx.validatedFiles.xxx.filepath`
- `ctx.validatedFiles.xxx.name` -> `ctx.validatedFiles.xxx.originalFilename`
- `ctx.validatedFiles.xxx.type` -> `ctx.validatedFiles.xxx.mimetype`
=> build(deps): bump formidable from 2.0.0-canary.20200504.1 to 2.0.1

packages/code-gen/src/generate-types.js, packages/code-gen/src/generator/apiClient/templates/apiClientFile.tmpl, packages/code-gen/src/generator/apiClient/templates/apiClientFn.tmpl, packages/code-gen/src/generator/common.js, packages/code-gen/src/generator/reactQuery/templates/reactQueryFile.tmpl, packages/code-gen/src/generator/reactQuery/templates/reactQueryFn.tmpl, packages/code-gen/test/e2e-server.test.js, types/generated/common/compas.d.ts
- Removed Axios.cancelToken support. Please use the `signal` option.
- Requires react-query 3.30.0 or higher
=> feat(code-gen): use abort signal in api clients

packages/code-gen/src/generator/common.js
This fixes an issue with React Native which requires React imports at the top of every file that includes JSX.
When missing, React Native will throw `Can't find variable: React` even when React is not directly used, however, it is still required to translate JSX.
=> fix(code-gen): add React import to reactQuery template

gen/testing.js, packages/code-gen/src/App.d.ts, packages/code-gen/src/App.js, packages/code-gen/src/generate.d.ts, packages/code-gen/src/generate.js, packages/code-gen/src/generator/errors.d.ts, packages/code-gen/src/generator/openAPI/generator.d.ts, packages/code-gen/src/generator/openAPI/generator.js, packages/code-gen/src/generator/openAPI/generator.test.js, packages/code-gen/src/generator/openAPI/index.d.ts, packages/code-gen/src/generator/openAPI/index.js, packages/code-gen/src/generator/openAPI/transform.d.ts, packages/code-gen/src/generator/openAPI/transform.js, packages/store/.npmignore, scripts/generate.js, src/generate.js, types/generated/common/types.d.ts
Closes #574
Contents:
Wish list:
Example (generator call):
```node
const app = new App({
verbose: true,
});
await app.generateOpenApi({
inputPath: "./generated/testing/server",
outputFile: "./generated/testing/server/common/openapi.json",
enabledGroups: ["server", "group"],
openApiOptions: {
version: "0.0.99",
title: "Compas Test server OpenAPI Docs",
description: "Lorem ipsum",
servers: ["https://api.compasjs.com"]
},
});
```
=> feat(code-gen): generate openAPI spec based on compas structure 

packages/code-gen/test/e2e-server.test.js, packages/server/src/app.d.ts, packages/server/src/app.js, packages/stdlib/src/error.d.ts, packages/stdlib/src/error.js, packages/stdlib/src/error.test.js, packages/store/src/session-store.d.ts
Instead of 'errors' we use the 'cause' property here as well for consistency reasons with all other error formats
Closes #1205
- Renamed `AppError#originalError` to `AppError#cause`
- Format also uses `cause` as the key when formatting `AppError` instead of `originalError`
=> feat(stdlib): support formatting Aggregate errors

packages/store/src/queue.d.ts, packages/store/src/queue.js
References #1344
As the option implies this disables any sorting when picking up jobs. Which equals to ignoring the 'priority' and 'scheduledAt' properties of jobs. Resulting in a much faster way of picking up jobs, for example when generating bursts of a million jobs. Which often results in slow seq scans and in memory sorting by postgres.
A 'normal' workload consisting of transactional inserted jobs that are immediately picked up by Postgres should most likely use the existing indices and don't need this option.
Seeing improvements of 30 seconds to just a few milliseconds when picking up a job.
=> feat(store): add `unsafeIgnoreSorting` as a queue worker option

docs/features/session-handling.md, packages/stdlib/src/error.d.ts, packages/stdlib/src/error.js, packages/store/index.d.ts, packages/store/index.js, packages/store/package.json, packages/store/src/session-store.js, packages/store/src/session-transport.d.ts, packages/store/src/session-transport.js, packages/store/src/session-transport.test.js
Support reading access from Authorization headers. And support reading and writing tokens from and to cookies.
TODO:
Testing this is going to be a bit of a pain, since there is no easy way to mock `ctx.cookies.get()` and `.set()` that are worth to write since we still need to test the full integration.
=> feat(store): add session transports

packages/code-gen/src/generator/sql/query-builder.js, packages/code-gen/test/sql.test.js, packages/store/src/file-group.test.js, packages/store/src/generated/common/anonymous-validators.d.ts, packages/store/src/generated/common/anonymous-validators.js, packages/store/src/generated/database/file.d.ts, packages/store/src/generated/database/file.js, packages/store/src/generated/database/fileGroup.d.ts, packages/store/src/generated/database/fileGroup.js, packages/store/src/generated/database/job.d.ts, packages/store/src/generated/database/job.js, packages/store/src/generated/database/session.d.ts, packages/store/src/generated/database/session.js, packages/store/src/generated/database/sessionStore.d.ts, packages/store/src/generated/database/sessionStore.js, packages/store/src/generated/database/sessionStoreToken.d.ts, packages/store/src/generated/database/sessionStoreToken.js, packages/store/src/generated/store/validators.d.ts, packages/store/src/generated/store/validators.js, packages/store/src/session-store.test.js, packages/store/src/session-transport.test.js, types/generated/common/types.d.ts
Closes #1394
- This should be done in the new `where.viaXxx`. Giving more flexibility by combining it with `where.$or` and allowed usage in update and delete queries.
- Note that the query builder functions validate their inputs, so if you have decent test coverage, your tests should be able to catch most of your usages for you.
=> feat(code-gen): remove 'via' traversers from the query builders

packages/code-gen/src/generator/reactQuery/templates/reactQueryFn.tmpl
This also splits the query key to separate the `group` and `name`. This allows to invalidate a whole group of routes.
Closes #1422
- The `useFooBar.baseKey()` functions now returns an array, and is spread when used in `useFooBar.queryKey()`
=> feat(code-gen): make reactQuery generator compatible with react-query@v4

docs/releases/0.0.180.md, packages/code-gen/src/generator/sql/query-builder.js, packages/code-gen/src/generator/sql/where-type.js, packages/store/index.d.ts, packages/store/index.js, packages/store/src/generated/database/file.d.ts, packages/store/src/generated/database/file.js, packages/store/src/generated/database/fileGroup.d.ts, packages/store/src/generated/database/fileGroup.js, packages/store/src/generated/database/job.d.ts, packages/store/src/generated/database/job.js, packages/store/src/generated/database/sessionStore.d.ts, packages/store/src/generated/database/sessionStore.js, packages/store/src/generated/database/sessionStoreToken.d.ts, packages/store/src/generated/database/sessionStoreToken.js, packages/store/src/generator-helpers.d.ts, packages/store/src/generator-helpers.js, packages/store/src/session-store.test.js
Closes #1465
- `queryXxx().execRaw` has some output differences, verify your usages.
=> feat(code-gen,store): migrate query builder to generator helper

.gitignore, docs/references/cli.md, packages/cli/src/cli/loader.d.ts, packages/cli/src/cli/loader.js, packages/cli/src/cli/utils.d.ts, packages/cli/src/cli/utils.js, packages/cli/src/compas/commands/check-env.js, packages/cli/src/compas/commands/docker.js, packages/cli/src/compas/commands/lint.js, packages/code-gen/src/builders/DateType.d.ts, packages/code-gen/src/builders/DateType.js, packages/lint-config/index.js, packages/store/src/generator-helpers.d.ts, packages/store/src/generator-helpers.js, scripts/create-release.js, scripts/release.js
Closes #1429
- JSDoc related ESLint rules are enabled by default locally now, they were already enabled on `CI=true`.
- Add `.cache` to your `.gitignore`. Or specify another ESLint cache directory via `--eslint-cache-location`.
=> feat(cli): use ESLint cache, default enable JSDoc rules for `compas lint`

package.json, packages/cli/package.json, packages/code-gen/package.json, packages/code-gen/src/generator/openAPI/generator.d.ts, packages/code-gen/src/generator/openAPI/generator.js, packages/code-gen/src/generator/openAPI/index.d.ts, packages/code-gen/src/generator/openAPI/index.js, packages/code-gen/src/generator/openAPI/transform.d.ts, packages/code-gen/src/generator/openAPI/transform.js, packages/code-gen/test/e2e/openapi.test.js, packages/code-gen/test/e2e/route-invalidation.test.js, packages/code-gen/test/utils.test.js, packages/lint-config/package.json, packages/server/package.json, packages/stdlib/package.json, packages/store/package.json, src/testing.js
Extend the generator with (security) pass-through properties. Also make generator output more strict (and clean).
Target spec
```js
await app.generateOpenApi({
inputPath: "./generated/testing/server",
outputFile: "./generated/testing/server/common/openapi.json",
enabledGroups: ["server", "group"],
openApiExtensions: {
version: "0.0.99",
title: "Compas Test server OpenAPI Docs",
description: "Lorem ipsum",
servers: [{ url: "https://api.compasjs.com" }],
components: {
securitySchemes: {
production: {
type: "oauth2",
flows: {
clientCredentials: {
tokenUrl: "https://api.compasjs.com/token",
scopes: {
read: "Allow to read",
},
},
},
},
acceptance: {
type: "oauth2",
flows: {
clientCredentials: {
tokenUrl: "https://api.compasjs.com/token",
scopes: {
read: "Allow to read",
write: "Allow to …
```
=> feat(code-gen): openApi generator more strict and extend

packages/cli/src/code-mod/constants.js, packages/cli/src/code-mod/mods/v0.0.142.js, packages/code-gen/src/generator/openAPI/generator.js, packages/code-gen/src/generator/openAPI/index.js, packages/code-gen/src/generator/openAPI/transform.js, packages/code-gen/src/template.js, packages/lint-config/index.js, packages/store/src/queue.js, packages/store/src/session-store.js
- Linter prefers `object` over `Object`, `boolean` over `Boolean`, `Record<string,number>[]` over `Array<Object<string, number>>` etc. The linter will try to autofix this, but may require multiple runs.
=> feat(lint-config): add preferredTypes for primitives, objects and records

docs/features/logger-and-events.md, packages/cli/src/code-mod/constants.d.ts, packages/code-gen/src/generator/openAPI/index.d.ts, packages/code-gen/src/generator/openAPI/transform.d.ts, packages/code-gen/src/template.d.ts, packages/stdlib/index.d.ts, packages/stdlib/index.js, packages/stdlib/src/logger/logger.d.ts, packages/stdlib/src/logger/logger.js, packages/stdlib/src/logger/logger.test.js, packages/stdlib/src/utils.js, packages/stdlib/types/advanced-types.d.ts, packages/store/src/queue.d.ts
We need this because loggers can be created via Compas internals like the log middleware provided by @compas/server.
Closes #1539
- Removed support for `pinoOption` via `newLogger`. Pass these to `setGlobalLoggerOptions` as `pinoTransport` and `pinoDestination`.
=> feat(stdlib): add `setGlobalLoggerOptions` and 'extendGlobalLoggerContext`

docs/.vitepress/config.js
This was always wrong because it uses git checkout time, instead of last changed time.
=> chore(docs): remove last updated from pages

docs/features/file-handling.md, packages/code-gen/src/generator/router/invalidations.js, packages/store/index.d.ts, packages/store/index.js, packages/store/src/files.d.ts, packages/store/src/files.js, packages/store/src/files.test.js, packages/store/src/query.d.ts
Signed access to a specific file id, with an expiration.
Like the session store, this uses its own signing internally. We may want to expose this logic at some point and deprecate these functions.
This is a big step in dropping cookie support.
References #1307
TODO;
=> feat(store): add support for file access tokens

packages/code-gen/src/builders/OmitType.d.ts, packages/code-gen/src/builders/OptionalType.d.ts, packages/code-gen/src/builders/PickType.d.ts, packages/code-gen/src/builders/SearchableType.d.ts, packages/code-gen/src/generate.d.ts, packages/code-gen/src/generate.js, packages/code-gen/src/generator/structure.js
It only shaked out unused groups, but not unused types in a group
=> fix(code-gen): correctly shake out unused types in dumped api structure

docs/features/test-and-bench-runner.md, docs/references/cli.md, packages/cli/src/compas/commands/test.js, packages/cli/src/testing/config.js, packages/cli/src/testing/runner.js, packages/cli/src/testing/runner.test.js, packages/cli/src/testing/state.d.ts, packages/cli/src/testing/state.js, test/config.js
- All tests now require at least a single assertion or registration of a subtest
=> feat(cli): remove `enforceSingleAssertion` option from test config

docs/features/code-gen-sql.md, docs/index.md, packages/code-gen/src/generator/sql/query-basics.js, packages/code-gen/test/e2e/sql.test.js, packages/store/src/files.d.ts, packages/store/src/files.js, packages/store/src/files.test.js, packages/store/src/generated/database/file.d.ts, packages/store/src/generated/database/file.js, packages/store/src/generated/database/fileGroup.d.ts, packages/store/src/generated/database/fileGroup.js, packages/store/src/generated/database/index.d.ts, packages/store/src/send-transformed-image.test.js
Closes #1091
- Entities that use soft delete should use `queries.entityUpdate(sql, { update: { deletedAt: new Date() }, where, })` instead of `queries.entityDelete`
- The generated `queries.entityDeletePermanent`
is removed, and instead `queries.entityDelete` will always permanently delete a record, even if it was soft deleted.
=> feat(code-gen): cleanup soft delete support

packages/code-gen/src/generate-types.js, packages/code-gen/src/generator/openAPI/index.js
Some scripts could have imported the structure file and then generated a new version before calling `generateTypes` or `generateOpenAPI`. These two would then use the ES Module cached version, instead of using the newly generated version.
Closes #1699
=> fix(code-gen): import structure without cache in `generateTypes` and `generateOpenAPI`

packages/eslint-plugin/index.js, packages/eslint-plugin/lint-rules/check-event-name.js, packages/eslint-plugin/test/check-event-name.js, packages/eslint-plugin/test/rules.test.mjs
Validates if the value passed to `eventStart` can be derived from the function name.
Closes #1713
- Enabled the `@compas/check-event-name` rule in `@compas/full` ESLint config.
=> feat(eslint-plugin): add check-event-name rule

packages/code-gen/src/generator/common.js, packages/code-gen/src/generator/openAPI/generator.js, packages/server/src/app.d.ts, packages/server/src/app.js, packages/server/src/app.test.js, packages/server/src/middleware/error.js, packages/server/src/middleware/log.js, packages/stdlib/src/error.d.ts
Closes #1757
- The `stack` and `cause` properties are never sent to the client.
- Error responses should have a `requestId` property, referencing to the logs with `stack` and `cause` properties.
=> feat(server): remove `leakError` support

packages/code-gen/src/builders/StringType.js
=> feat(code-gen): add explicit error for empty `T.string().oneOf()` values

.env, .github/workflows/main-checks.yml, .github/workflows/pr-checks.yml, docs/features/postgres-and-minio.md, docs/references/cli.md
- `POSTGRES_HOST` and `MINIO_URI` should use `127.0.0.1` instead of `localhost` when using Node.js 18+.
=> chore: support Node.js 18

packages/code-gen/src/builders/FileType.d.ts, packages/code-gen/src/builders/FileType.js, packages/store/src/files.d.ts, packages/store/src/files.js, packages/store/src/send-transformed-image.d.ts, packages/store/src/send-transformed-image.js, packages/store/src/send-transformed-image.test.js
Also updates the doc blocks for `FileType#mimeTypes` and `createOrUpdateFile` to reference the appropriate content / mime type list
Closes #1801
=> feat(store,code-gen): support image/avif in `sendTransformedImage`

scripts/changelog.js
For example `Close`, `Reference`, `BREAKING CHANGE` and `BREAKING CHANGES`
=> chore(changelog): support keywords with and without trailing `S`

packages/cli/src/testing/runner.js
=> feat(cli): improve printing of 'actual' values in `t.ok` and `t.notOk`

packages/server/src/app.test.js, packages/server/src/middleware/error.js
=> feat(server): return `stack` and `cause` of errors when not in production

packages/code-gen/src/crud/e2e/nested.test.js, packages/code-gen/src/crud/partials/routes.js, packages/code-gen/src/crud/route-implementer.js
Creating multiple records in a `oneToOne` relation gives unexpected results. It also prevents usage of `single` and indirectly `update` and `delete` routes, since the `single` checks if only one record is returned from the provided builder.
/cc @tjonger 
References #1843
=> feat(code-gen): add check to prevent double `oneToOne` creation

examples/session-handling/src/generated/common/router.js, packages/code-gen/src/generator/router/templates/routerFile.tmpl, packages/code-gen/test/e2e/server-and-client.test.js
This is due to the new structure api dump which dumps the resolved references instead of the intermediate references.
=> fix(code-gen): resolve out of group refs in router generator

packages/server/src/middleware/error.js
Ensure log entry `level` property is correct for AppError.serverErrors
=> fix(server): ensure log level is inherited from AppError

examples/session-handling/src/generated/common/anonymous-validators.js, examples/session-handling/src/generated/common/types.d.ts, packages/code-gen/src/generator/sql/query-builder.js, packages/code-gen/test/e2e/sql.test.js, packages/store/src/generated/common/anonymous-validators.d.ts, packages/store/src/generated/common/anonymous-validators.js, packages/store/src/generator-helpers.js, types/generated/common/types.d.ts
=> feat(code-gen): support selecting a set of fields in the query builder

packages/code-gen/src/structure/structureHoistNamedItems.js, packages/code-gen/src/structure/structureHoistNamedItems.test.js
If a named item was copied as is in the structure, and then mutated, it would override the initial named item.
=> fix(code-gen): correctly prioritze existing named items in the structure

packages/compas/index.d.ts, packages/compas/index.js, packages/compas/package.json, packages/compas/src/exports/cli.d.ts, packages/compas/src/exports/cli.js, packages/compas/src/exports/code-gen.d.ts, packages/compas/src/exports/code-gen.js, packages/compas/src/exports/exports.test.js, packages/compas/src/exports/server.d.ts, packages/compas/src/exports/server.js, packages/compas/src/exports/stdlib.d.ts, packages/compas/src/exports/stdlib.js, packages/compas/src/exports/store.d.ts, packages/compas/src/exports/store.js
This gives us flexibility to add other features to this package.
However, this hurts discoverability a bit, since now you have to check the 5 specific exports for the thing you need.
- Change any direct `compas` import to `compas/pkg` or `@compas/pkg`.
=> feat(compas): use sub entrypoints (`compas/cli`) instead of a single entrypoint

examples/session-handling/src/generated/common/structure.js, packages/cli/src/generated/common/structure.d.ts, packages/cli/src/generated/common/structure.js, packages/code-gen/src/App.d.ts, packages/code-gen/src/App.js, packages/code-gen/src/generated/common/structure.d.ts, packages/code-gen/src/generated/common/structure.js, packages/code-gen/src/generator/apiClient/templates/apiClientFn.tmpl, packages/code-gen/src/generator/types.js, packages/code-gen/test/environment/react-native.test.js, packages/store/src/generated/common/structure.d.ts, packages/store/src/generated/common/structure.js
This is done by accepting an `environment.clientRuntime` option via the generate options.
Closes #1908
=> fix(code-gen): correctly generate types and api client for file uploads via React Native

docs/features/test-and-bench-runner.md, packages/cli/src/compas/commands/test.js, packages/cli/src/testing/config.js, packages/cli/src/testing/runner.js, packages/cli/src/testing/state.test.js, packages/cli/src/testing/utils.js, packages/stdlib/index.d.ts, packages/stdlib/index.js, packages/stdlib/src/logger.d.ts, packages/stdlib/src/logger.js, src/testing.js
Introduces `compas test --with-logs` to enable all logs.
Closes #1930
BREAKING CHANGES:
- When tests are executed via `compas test`, the info logs are suppressed by default. To enable all info logs, either use `compas test --with-logs` or run a specific test file with `mainTestFn` via `compas run ./file.test.js`.
=> feat(cli): suppress info logs by default.

packages/store/src/postgres.js
Closes #1928
- `process.env.PGDATABASE` is used before `process.env.APP_NAME` as the database name for Postgres connections
=> feat(store): support Postgres native environment variables

examples/with-auth/package.json, package-lock.json
with-auth was missing axios in packages, required for testing.
Closes https://github.com/compasjs/compas/issues/2106
=> fix(examples): with-auth added axios as dev package

packages/code-gen/src/generator/reactQuery/templates/reactQueryFn.tmpl
Closes #2114
- `useFooBar.invalidate()` does not accept an `AxiosInstance` anymore.
=> fix(code-gen): remove axiosInstance as param on `useFooBar.invalidate` calls

packages/create-compas/src/template.js
=> fix(create-compas): write template tar to temp directory before extracting

package-lock.json, packages/cli/src/compas/commands/lint.js, packages/eslint-plugin/package.json
This enables the new `--cache` and `--cache-location` features for Prettier. We already use these for a bit with ESLint.
In this repo we get the following results (on only a few runs), runs without cache already use the ESLint cache features:
- `compas generate`:
- Before: ~18.5 seconds
- Building cache: ~20.5 seconds
- With cache: ~13.5 seconds
- `compas lint`:
- Before: ~7.8 seconds
- Building cache: ~10 seconds
- With cache: ~1.8 seconds
=> feat(cli,eslint-plugin): bump Prettier

packages/store/src/testing.js
This captures the stacktrace before executing the query, improving the experience while debugging tests.
=> feat(store): enable Postgres library debug mode for test databases

packages/server/src/app.test.js, packages/stdlib/src/error.js
Added all possible fields of Postgres errors, a bunch of them will be undefined, which are skipped when serialized to JSON. When running in debug mode, the query & parameters will be added by the Postgres library, so these will be added as well.
The formatted Axios error is reshaped, adding request headers and preventing response streams from being added. The request headers are added and the Au
- `axios.requestPath` and `axios.requestMethod` are replaced by `axios.request.path` and `axios.request.method`.
- `axios.responseStatus`and `axios.responseBody` are replaced by `axios.response.status`, `axios.response.body`.
- `axios.responseHeaders` is removed from the error to prevent session tokens in the logs by default.
=> feat(stdlib): completer Axios and Postgres error formatting by AppError#format

packages/store/src/file.js
S3 supports deleting up to 1000 objects in a single request, we batch the to be deleted items in multiple requests when necessary and fire these requests in parallel.
=> fix(store): batch object deletes in `fileSyncDeletedWithObjectStorage`

examples/default/commands/generate.js, examples/with-auth/commands/generate.js
subCommand `generate` doesnt exist in the defined subCommands and should be `application`.
=> fix(examples): correct subCommand check
