packages/cli/src/commands/visualise.js
packages/cli/src/commands/visualise.test.js
packages/code-gen/src/internal-exports.js

cli: fix usage of code-gen internals in visualise

---

packages/cli/src/utils.js

The 'close' listener did run for processes that were killed, introducing a race condition where the new instance was set to 'undefined' instead of the existing one.
We now wait on tree-kill before starting a new process, this fixes a race condition where a server may not be fully stopped yet, but a new process tries to listen on the same port.

cli: fix watch and restart behaviour of long running processes

---

packages/cli/src/commands/help.js
packages/cli/src/commands/proxy.js

This enabled response header printing, to get a better understanding of what is happening when things go haywire.

cli: add verbose option to proxy

---

packages/code-gen/src/open-api-importer.js

code-gen: fix loading of patterns via OpenAPI spec

---

packages/code-gen/src/generator/sql/query-builder.js
packages/store/src/generated/query-builder.js

code-gen: add possible type results to the query builder functions

---

packages/cli/src/testing/printer.js

Refactored the test printer a bit with more earlier returns and added some comments on why the order things is as is.
This also closes #624 by skipping sub trees even for test suites if nothing failed. We would print the first 2 levels of all trees when a failure happened, and the full sub tree to the specific failures. Now we only print the first single level of the tree and still do the full sub tree to a failure.
Fixes #624

cli: cleaner test output on failed results

---

packages/code-gen/src/generator/sql/structure.js

code-gen: fix float support in sql structure generator

---

packages/cli/scripts/test.js

The test runner did not exit when a worker would fail in either the global setup or teardown execution.
Since we can't know when a message will arrive, the runner just waited till all workers posted their results back. A failing worker won't post anything, so it was an infinite timeout loop.
Know we exit as soon as possible when a worker exits with an exit code other than 0.
Closes #666

fix(cli): proper exit on test worker failure

---

packages/code-gen/src/generator/sql/query-builder.js
packages/store/src/generated/database/file.js
packages/store/src/generated/database/fileGroup.js
packages/store/src/generated/database/fileGroupView.js

Should result in the diffs only being related to the changed relations.
Closes #678

feat(code-gen): stable query builder join key generation

---

packages/stdlib/src/error.js

fix(stdlib): handle 'undefined' in AppError#format

---

packages/code-gen/src/generator/apiClient/templates/apiClientFile.tmpl
packages/code-gen/src/generator/apiClient/templates/apiClientFn.tmpl

fix(code-gen): jsdoc lint compliant output of the api client

---

packages/code-gen/src/generator/sql/where-type.js
packages/code-gen/test/sql.test.js
packages/store/src/generated/database/file.js
packages/store/src/generated/database/fileGroup.js
packages/store/src/generated/database/fileGroupView.js
packages/store/src/generated/database/job.js
packages/store/src/generated/database/session.js

fix(code-gen): sql where notIn should return all results on empty array

---

packages/cli/scripts/test.js
packages/cli/src/testing/runner.js
packages/cli/src/testing/runner.test.js
packages/cli/src/testing/test.js
packages/cli/src/utils.js

feat(cli): ignore test runner timeout when detecting open inspector

---

packages/code-gen/src/generator/router/trie.js

feat(code-gen): throw error on duplicate routes

---

packages/code-gen/src/builders/utils.js

feat(code-gen): throw on inferred array with more than a single element

---

packages/store/index.d.ts

fix(store): add TS type definition for `updateFileGroupOrder`

---

packages/code-gen/src/generator/apiClient/templates/apiClientFn.tmpl

fix(code-gen): use formatData.append for multipart body in the api client

---

packages/insight/index.d.ts
packages/insight/src/events.test.js
packages/insight/src/logger/logger.bench.js
packages/insight/src/logger/logger.js
packages/insight/src/logger/writer.js
packages/stdlib/src/utils.js

Also allows disabling info and error loggers

feat(insight): support error formatting for Github actions

---

gen/code-gen.js
packages/code-gen/src/generated/common/anonymous-validators.js

fix(code-gen): default for internal settings is correct for the type definition

---

packages/stdlib/index.js
packages/stdlib/src/env.js
packages/stdlib/src/env.test.js

See the docs for more information.
Closes #791

feat(stdlib): add helpers to calculate cookie and cors urls

---

packages/server/index.d.ts
packages/server/package.json
packages/server/src/middleware/body.js
packages/server/src/middleware/body.test.js
packages/server/src/middleware/log.js
yarn.lock

Gives us the opportunity to catch and handle errors normally.
Closes #805

feat(server): replace koa-body with just co-body

---

gen/testing.js
packages/code-gen/src/generated/common/anonymous-validators.js
packages/code-gen/src/generator/validator.js
packages/store/src/generated/common/anonymous-validators.js

fix(code-gen): remove stacktraces from anyOf sub errors

---

packages/store/src/queue.js

fix(store): call eventStart on event passed to handler

---

packages/cli/src/commands/help.js

feat(cli): check if multiple versions of the stdlib are installed

---

packages/cli/scripts/bench.js
packages/cli/src/benchmarking/runner.js
packages/store/src/query.bench.js

bench(store): add benchmarks for the query function

---

packages/cli/src/commands/proxy.js

fix(cli): improve proxy error messages

---

packages/cli/scripts/lint.js

feat(cli): support running prettier when no files are found

---

packages/stdlib/src/utils.js

feat(stdlib): load .env.local if exists

---

packages/cli/src/commands/help.js

feat(cli): add --check, check if .env.local is ignored

---

packages/code-gen/src/generator/router/templates/routeMatcher.tmpl
packages/code-gen/src/generator/router/templates/routerFile.tmpl
packages/code-gen/test/e2e-server.test.js

feat(code-gen): send 400 on param decode errors

---

gen/code-gen.js
gen/testing.js
packages/code-gen/index.d.ts
packages/code-gen/src/builders/FileType.js
packages/code-gen/src/generated/common/anonymous-validators.js
packages/code-gen/src/generated/common/types.js
packages/code-gen/src/generator/validator.js
packages/code-gen/test/e2e-server.test.js

feat(code-gen): add mime validator support to T.file()

---

.github/codecov.yml
packages/cli/src/commands/help.js
packages/cli/src/migrate/index.js
packages/cli/src/migrate/migrate.test.js

feat(cli): support loading connection settings from a relative js file

---

packages/code-gen/test/sql.test.js

chore(code-gen): add test for query-builder nested limit

---

packages/cli/src/commands/help.js
packages/cli/src/migrate/index.js

feat(cli): add migrate --keep-alive-without-lock

---

packages/code-gen/src/builders/RouteBuilder.js
packages/store/src/file-cache.test.js

feat(code-gen): throw nice error on optional route parameters

---

packages/code-gen/src/generator/reactQuery/templates/reactQueryFn.tmpl

feat(code-gen): accept a object as argument in generated 'useQuery' hooks

---

packages/cli/src/testing/runner.js
packages/cli/src/testing/runner.test.js

fix(cli): prevent 'caughtException' overwriting by 'enforceSingleAssertion'

---

packages/cli/src/commands/docker.js

This prevents confusing long waits.
Closes #965

feat(cli): spawn 'docker pull' when container needs to be created

---

packages/cli/src/code-mod/mods/v0.0.146.js
packages/code-gen/src/generator/sql/query-basics.js
packages/code-gen/test/sql.test.js
packages/store/src/generated/database/file.js
packages/store/src/generated/database/fileGroup.js
packages/store/src/generated/database/fileGroupView.js
packages/store/src/generated/database/job.js
packages/store/src/generated/database/session.js

Superseded by the generated query builders.
Closes #966

feat(code-gen): remove entitySelect generation

---

packages/cli/src/testing/events.js
packages/cli/src/testing/events.test.js

This used the old implementation

fix(cli): let newTestEvent use 'newEvent' from stdlib

---

packages/store/index.d.ts
packages/store/src/postgres.js
packages/store/src/testing.js
packages/store/src/testing.test.js

feat(store): createTestPostgresDatabase accepts sql connection options

---

scripts/changelog.js

By including breaking changes from commit messages, the need for custom release notes will drop.
This also helps the person do the release decide on the correct new version number to use.

chore(changelog): improve changelog with breaking change handling

---

packages/server/src/middleware/sendFile.js
packages/server/src/middleware/sendFile.test.js

feat(server): sendFile support If-Modified-Since

---

packages/code-gen/src/generator/apiClient/templates/apiClientFn.tmpl
packages/code-gen/src/generator/reactQuery/templates/reactQueryFn.tmpl
packages/code-gen/src/generator/types.js

This know works correctly for:
- boolean
- number
- array
Closes #1047

fix(code-gen): handle convert when generating types.

---

docs/api/store.md
packages/store/index.d.ts
packages/store/src/files.js

fix(store): add Buffer to types of source for createOrUpdateFile

---

packages/store/src/postgres.js

fix(store): use connection defaults when creating postgres database

---

packages/code-gen/src/generator/validator.js

fix(code-gen): throw on unknown type in validators

---

lerna.json
package.json
packages/cli/src/utils.test.js
scripts/release.js
yarn.lock

Can't really test it without publishing, so hope that it all works as expected. This is directly the biggest downside of dropping Lerna ;)
Closes #1053

chore: drop lerna, create custom release script

---

gen/testing.js
migrations/003-user-post.sql
packages/cli/types/advanced-types.d.ts
packages/code-gen/src/generator/sql/structure.js
packages/code-gen/test/sql.test.js
types/generated/common/types.d.ts

fix(code-gen): allow searchable on references

---

contributing.md
packages/code-gen/src/generator/sql/partial-type.js
types/generated/common/types.d.ts

fix(code-gen): nullable types on sql insert partials

---

docs/.vitepress/config.js
docs/features/logger-and-events.md
docs/features/typescript-setup.md

feat(docs): add TS setup & logger and events

---

docs/.vitepress/config.js
docs/features/http-server.md

feat(docs): add http server document

---

packages/server/src/middleware/session.js

Rolling sessions are just too quick as a default, and renew option is too slow. So we add a way in between.
If 'renew' is a number, it determines the amount of seconds between resetting the expire date with the 'maxAge'. It defaults to 30 seconds. Which results in each request after 30 seconds containing a 'Set-Cookie' header.

feat(server): support renewing sessions every x seconds

---

packages/code-gen/src/generator/sql/partial-type.js
packages/code-gen/test/sql.test.js
packages/store/src/generated/database/file.js
packages/store/src/generated/database/fileGroup.js
packages/store/src/generated/database/job.js
packages/store/src/generated/database/session.js

fix(code-gen): throw explicit error on empty sql update clause

---

packages/code-gen/src/generator/apiClient/templates/apiClientFn.tmpl

feat(code-gen): don't output params & data if not used in the api client

---

packages/code-gen/src/generator/reactQuery/templates/reactQueryFn.tmpl

feat(code-gen): redo options.enabled of react-query generator

---

docs/.vitepress/config.js
docs/features/code-gen-validators.md
docs/features/logger-and-events.md

feat(docs): add code-gen setup and validators

---

packages/cli/src/testing/printer.js
packages/stdlib/src/error.test.js

feat(cli): als print passed test assertions around the failed assertion

---

packages/stdlib/src/error.d.ts
packages/stdlib/src/error.js
packages/stdlib/src/error.test.js

feat(stdlib): add AppError#format support for various primitives

---

packages/store/src/send-transformed-image.js
packages/store/src/send-transformed-image.test.js

fix(store): saving of transforms in `sendTransformedImage`

---

packages/store/src/queue.js
packages/store/src/queue.test.js

feat(store): remove `averageTimeToCompletion` from `JobQueueWorker`

---

packages/store/src/queue.d.ts
packages/store/src/queue.js
packages/store/src/queue.test.js

This removes all jobs completed longer than 'maxAgeInDays' ago.

feat(store): add `JobQueueWorker.clean()` method

---

packages/code-gen/src/generator/index.d.ts
packages/code-gen/src/generator/openAPI/generator.js
packages/code-gen/src/generator/router/index.d.ts
packages/code-gen/src/generator/sql/where-type.d.ts

Also this will be PR#1000 to be merged/closed 🥳

fix(code-gen): openapi exporter support for multiple methods within the same path

---

docs/index.md
packages/code-gen/index.d.ts
packages/code-gen/index.js
packages/code-gen/src/loaders.d.ts
packages/code-gen/src/loaders.js

feat(code-gen): rename `loadFromRemote` to `loadApiStructureFromRemote`

---

packages/code-gen/src/generator/router/index.js
packages/code-gen/src/generator/types.js
types/generated/common/types.d.ts
yarn.lock

fix(code-gen): fix types of validated files in the router

---

docs/.vitepress/config.js
docs/api/store.md
docs/features/file-handling.md
gen/code-gen.js
packages/store/package.json
packages/store/src/files.js
packages/store/src/files.test.js
test/config.js
yarn.lock

feat(store): infer and validate content-type support in createOrUpdateFile

---

docs/.vitepress/config.js
docs/features/code-gen-sql.md
packages/code-gen/src/generator/sql/where-type.js
packages/code-gen/test/sql.test.js
packages/stdlib/src/error.js
packages/store/src/files.d.ts
packages/store/src/files.js
packages/store/src/generated/common/anonymous-validators.d.ts
packages/store/src/generated/common/anonymous-validators.js
packages/store/src/generated/database/file.js
packages/store/src/generated/database/fileGroup.js
packages/store/src/generated/database/sessionStore.js
packages/store/src/generated/database/sessionStoreToken.js
packages/store/src/generator-helpers.d.ts
packages/store/src/generator-helpers.js
packages/store/src/queue.js
packages/store/src/session-store.js
packages/store/src/session-transport.js
packages/store/src/session-transport.test.js
src/testing.js
test/code-gen/sql.test.js
types/generated/common/compas.d.ts
types/generated/common/types.d.ts

feat(code-gen,store): support viaXxx in where clause

---

packages/store/src/queue.js

feat(store): skip `eventStop` on Compas internal handled jobs

---

.eslintignore
.prettierignore
docs/.vitepress/config.js
docs/features/cli-watcher.md
packages/cli/index.d.ts
packages/cli/index.js
packages/cli/src/utils.js
packages/cli/src/watcher.d.ts
packages/cli/src/watcher.js
packages/code-gen/src/generator/errors.js
packages/stdlib/src/config-loader.js
packages/store/src/files.js

feat(cli): add watcherKillProcess and watcherRun abstraction

---

packages/cli/src/cli/commands/init.d.ts
packages/cli/src/cli/commands/init.js
packages/cli/src/cli/logger.d.ts
packages/cli/src/cli/logger.js
packages/cli/src/cli/types.d.ts
packages/cli/src/cli/types.js
packages/cli/src/commands/init.d.ts
packages/cli/src/commands/init.js
packages/cli/src/utils.js
packages/cli/src/watcher.d.ts
packages/stdlib/src/config-loader.d.ts

feat(cli): refactor init, add new logger and types

---

packages/cli/src/cli/commands/migrate.d.ts
packages/cli/src/cli/commands/migrate.js
packages/cli/src/cli/logger.js
packages/cli/src/cli/types.d.ts
packages/cli/src/cli/types.js
packages/cli/src/migrate/index.d.ts
packages/cli/src/migrate/index.js

feat(cli): use new system for migrate command

---

packages/cli/src/cli/commands/proxy.d.ts
packages/cli/src/cli/commands/proxy.js
packages/cli/src/commands/proxy.d.ts
packages/cli/src/commands/proxy.js

feat(cli): migrate proxy to new executor way

---

packages/cli/src/cli/commands/code-mod.d.ts
packages/cli/src/cli/commands/code-mod.js
packages/cli/src/commands/code-mod.js

feat(cli): migrate code-mod to new executor way

---

packages/cli/src/cli/help.js

feat(cli): check if command and flags are not conflicting with built-in help

---

docs/.vitepress/config.js
docs/features/cli.md
docs/features/code-gen-api.md
docs/features/code-gen-validators.md
docs/features/http-server.md
docs/features/lint-setup.md
docs/features/postgres-and-minio.md
docs/features/test-and-bench-runner.md
docs/features/typescript-setup.md
docs/getting-started.md
packages/cli/src/cli/help.js
packages/cli/src/compas/cli.js
packages/cli/src/compas/commands/code-mod.js
packages/cli/src/compas/commands/docker.js
packages/cli/src/compas/commands/init.js
packages/cli/src/compas/commands/lint.js
packages/cli/src/compas/commands/migrate.js
packages/cli/src/compas/commands/proxy.js
packages/cli/src/compas/commands/run.js

feat(cli): add some docs + improve various command descriptions

---

packages/cli/src/compas/commands/test.d.ts
packages/cli/src/compas/commands/test.js

feat(cli): migrate test and coverage commands to new cli

---

packages/cli/src/compas/commands/bench.d.ts
packages/cli/src/compas/commands/bench.js

feat(cli): migrate bench command to new cli

---

packages/code-gen/test/e2e-server.test.js
packages/server/src/app.d.ts
packages/server/src/app.js
packages/server/src/middleware/log.d.ts
packages/server/src/middleware/log.js

feat(server): add options to log middleware to log event name, query and param objects

---

docs/.vitepress/config.js
docs/features/cli.md
docs/references/cli.md
scripts/syncMetadata.js
src/cli-reference.js

At some point, we probably want to integrate this with the cli api's.
Closes #1462

feat(docs): add CLI reference to the docs

---

docs/references/cli.md
packages/cli/src/compas/commands/init.js

feat(cli): add '--lint-config' to compas init

---

packages/cli/src/compas/commands/lint.js

feat(cli): add informational logs to lint output

---

docs/references/cli.md
packages/cli/src/compas/commands/init.js

feat(cli): add `--gitignore` and `--all` support to `compas init`

---

packages/cli/src/cli/internal-commands/completions.d.ts
packages/cli/src/cli/internal-commands/completions.js
packages/code-gen/src/generator/sql/partial-type.js
packages/code-gen/test/e2e/sql.test.js
packages/store/src/generated/database/file.js
packages/store/src/generated/database/fileGroup.js
packages/store/src/generated/database/job.js
packages/store/src/generated/database/sessionStore.js
packages/store/src/generated/database/sessionStoreToken.js

feat(code-gen): generate errors on too much inserts

---

packages/cli/src/compas/commands/migrate.js

fix(cli): migrate keep-alive should use connection-settings

---

packages/code-gen/src/generator/openAPI/generator.js
packages/code-gen/src/generator/openAPI/transform.d.ts
packages/code-gen/src/generator/openAPI/transform.js
packages/code-gen/test/e2e/openapi.test.js

Closes https://github.com/compasjs/compas/issues/1577

feat(code-gen): support for reference types in query and params in openApi exporter

---

packages/cli/src/cli/loader.js

fix(cli): remove error log if command directory is not found

---

packages/code-gen/test/e2e/sql.test.js

When a jsonb field is optional, without default value. The inserted 'null' value is inserted as jsonb null and not as PG NULL. So test that behavior so any refactor of the insert queries will keep that behavior or be noted as a breaking change.
Closes #1600

test(code-gen): jsonb null insert behavior

---

scripts/syncMetadata.js

chore: add LICENSE to packages

---

packages/eslint-plugin/lint-rules/enforce-event-stop.js
packages/eslint-plugin/test/enforce-event-stop.js

fix(eslint-plugin): don't suggest enforce-event-stop after code paths that always leave a function

---

packages/cli/src/testing/printer.js

fix(cli): include failing assertions of subtests in failing test

---

.github/workflows/main-checks.yml
.github/workflows/pr-checks.yml
contributing.md
scripts/generate.js
src/generate.js

It now also includes linting + running Typescript
Closes #1692

chore(generate): convert internal script to internal command

---

packages/eslint-plugin/lint-rules/enforce-event-stop.js
packages/eslint-plugin/test/enforce-event-stop.js

fix(eslint-plugin): only error enforce-event-stop if `eventStart` is called

---

packages/server/src/middleware/body.js
packages/server/src/middleware/body.test.js

feat(server): handle file upload size limit errors

---

packages/stdlib/src/error.js
packages/stdlib/src/error.test.js

feat(stdlib): supported already formatted error in AppError#format

---

examples/session-handling/src/generated/common/anonymous-validators.js
packages/cli/src/generated/common/anonymous-validators.js
packages/code-gen/src/generated/common/anonymous-validators.js
packages/code-gen/src/generator/validator.js
packages/store/src/generated/common/anonymous-validators.js

feat(code-gen): only report first error in 'anyOf' validators

---

packages/code-gen/src/builders/RouteBuilder.js

feat(code-gen): hard error on duplicate route param

---

packages/code-gen/src/crud/CrudType.js
packages/code-gen/src/crud/e2e/basic.test.js
packages/code-gen/src/crud/event-implementer.js
packages/code-gen/src/crud/partials/events.js
packages/code-gen/src/crud/route-creator.js
packages/code-gen/src/crud/route-functions.js

chore(code-gen): add e2e tests for basic crud generation

---

packages/code-gen/src/crud/e2e/basic.test.js
packages/code-gen/src/crud/e2e/inline.test.js
packages/code-gen/src/crud/event-implementer.js
packages/code-gen/src/crud/partials/events.js
packages/code-gen/src/crud/route-creator.js
packages/code-gen/src/generate.js
packages/code-gen/src/generator/index.js
packages/code-gen/src/preprocessors/index.js

chore(code-gen): test crud inline + various fixes

---

packages/code-gen/src/crud/CrudType.js
packages/code-gen/src/crud/e2e/nested.test.js
packages/code-gen/src/crud/partials/routes.js
packages/code-gen/src/crud/preprocessor.js
packages/code-gen/src/crud/route-creator.js
packages/code-gen/src/crud/route-implementer.js

chore(code-gen): test crud nested + various fixes

---

packages/code-gen/src/crud/e2e/nested.test.js
packages/code-gen/src/crud/route-creator.js

feat(code-gen): add route invalidations to crud routes in a single group

---

docs/features/code-gen-crud.md
packages/code-gen/src/crud/e2e/modifiers.test.js
packages/code-gen/src/crud/partials/routes.js
packages/code-gen/src/crud/route-implementer.js

feat(code-gen): support crud modifiers

---

packages/code-gen/src/crud/e2e/basic.test.js
packages/code-gen/src/crud/partials/routes.js
packages/code-gen/src/crud/route-creator.js
packages/code-gen/src/generator/sql/where-type.d.ts
packages/code-gen/src/generator/sql/where-type.js

feat(code-gen): add support for filters on crud list routes

---

packages/store/src/query.js
packages/store/src/query.test.js

feat(store): support interpolating dates in stringifyQueryPart

---

docs/features/background-jobs.md
packages/store/index.d.ts
packages/store/index.js
packages/store/src/files-jobs.d.ts
packages/store/src/files-jobs.js
packages/store/src/files-jobs.test.js
packages/store/src/queue-worker-jobs.d.ts
packages/store/src/queue-worker-jobs.js
src/testing.js

feat(store): add `jobFileCleanup`

---

docs/features/background-jobs.md
packages/store/index.d.ts
packages/store/index.js
packages/store/src/session-store-jobs.d.ts
packages/store/src/session-store-jobs.js
packages/store/src/session-store-jobs.test.js

feat(store): add `jobSessionStoreCleanup`

---

.github/workflows/pr-checks.yml

chore(ci): expand on matrix combinations for test and coverage runs

---

docs/features/background-jobs.md
packages/store/index.d.ts
packages/store/index.js
packages/store/src/session-store-jobs.d.ts
packages/store/src/session-store-jobs.js
packages/store/src/session-store-jobs.test.js

feat(store): add `jobSessionStoreProcessLeakedSession`

---

packages/cli/package.json
packages/code-gen/package.json
packages/compas/package.json
packages/eslint-plugin/package.json
packages/server/package.json
packages/stdlib/package.json
packages/store/package.json
test/repo/package.json.test.js

feat: add package.json exports

---

packages/store/src/session-store.js
packages/store/src/session-store.test.js

feat(store): improve sessionStore signingKey validation error

---

src/testing.js

chore(tests): remove unnecessary offset added to sql time offset

---

package-lock.json
packages/create-compas/.npmignore
packages/create-compas/LICENSE
packages/create-compas/README.md
packages/create-compas/package.json
packages/create-compas/src/create-compas.d.ts
packages/create-compas/src/create-compas.js
packages/create-compas/src/create-compas.test.js
scripts/syncMetadata.js
test/repo/package.json.test.js

feat(create-compas): init package

---

docs/examples.md
examples/default/package.json
package-lock.json
packages/create-compas/src/arg-parser.d.ts
packages/create-compas/src/arg-parser.js
packages/create-compas/src/arg-parser.test.js
packages/create-compas/src/create-compas.js
packages/create-compas/src/help.d.ts
packages/create-compas/src/help.js

References #1907 
Closes #1965

feat(create-compas): add args parser

---

packages/create-compas/src/create-compas.js
packages/create-compas/src/create-compas.test.js

feat(create-compas): determine and check the output directory

---

examples/default/package.json
package-lock.json
packages/create-compas/package.json
packages/create-compas/src/arg-parser.d.ts
packages/create-compas/src/arg-parser.js
packages/create-compas/src/arg-parser.test.js
packages/create-compas/src/create-compas.js
packages/create-compas/src/create-compas.test.js
packages/create-compas/src/template.d.ts
packages/create-compas/src/template.js

Also resolves compas versions to latest.
Closes #1968

feat(create-compas): download github repo support

---

.github/workflows/main-checks.yml
.github/workflows/pr-checks.yml
.gitignore
packages/create-compas/src/template.js

And ignore the generated code of examples in this repo.

feat(create-compas): generate on template init

---

packages/code-gen/src/generator/apiClient/templates/apiClientFn.tmpl

feat(code-gen): add response data to response validator errors

---

packages/cli/src/testing/worker-internal.js
packages/cli/src/testing/worker-thread.js

feat(cli): add threadId to test runner logs

---

packages/cli/src/generated/common/anonymous-validators.js
packages/code-gen/src/generated/common/anonymous-validators.js
packages/store/src/file.js
packages/store/src/files-jobs.d.ts
packages/store/src/files-jobs.js
packages/store/src/generated/common/anonymous-validators.js
packages/store/src/object-storage.js
scripts/release.js

fix(store): explicit error on empty access token in `fileVerifyAccessToken`

---

packages/create-compas/src/create-compas.js
packages/create-compas/src/template.d.ts
packages/create-compas/src/template.js

feat(create-compas): check template existence, always use pretty logger

---

packages/cli/src/compas/commands/check-env.js

feat(cli): add docker and graphviz checks to 'compas check-env'

---

packages/code-gen/src/open-api-importer.js

Also remove top-level `requestBody.required` check.

feat(code-gen): openAPI import fixes for file uploads and string types

---

examples/with-auth/src/user/controller.test.js
packages/code-gen/src/generator/apiClient/templates/apiClientFile.tmpl
packages/code-gen/src/generator/apiClient/templates/apiClientFn.tmpl

Closes #2069
@rodymolenaar  `any` seems to be the default generic argument of `AxiosRequestConfig`, do you for see any problems if we generate without it?

feat(code-gen): accept full axios config in api client

---

packages/cli/src/compas/commands/docker.js

Open connections prevent the database from being dropped.
Closes #2087

feat(cli): `docker clean --project` tries to kill all open connections before cleaning

---

packages/server/src/middleware/cors.js

fix(#2182): ensure staging localhost CORS headers are present in response

---

docs/references/cli.md
packages/cli/src/compas/commands/run.js

fix(cli): don't try to run `compas run $directory`

---

packages/code-gen/src/builders/utils.js

Suggestions to help resolve the root cause of the issue faster.

feat(builders): utils expand inferred array error

---

benchmark/validate.bench.js
docs/generators/build-structure/types-and-validators.md
gen/code-gen-experimental.js
packages/code-gen/src/builders/AnyOfType.d.ts
packages/code-gen/src/builders/AnyOfType.js
packages/code-gen/src/experimental/generated/common/structure.json
packages/code-gen/src/experimental/generated/common/types.d.ts
packages/code-gen/src/experimental/generated/experimental/validators.js
packages/code-gen/src/experimental/processors/any-of.d.ts
packages/code-gen/src/experimental/processors/any-of.js
packages/code-gen/src/experimental/processors/reference-utils.d.ts
packages/code-gen/src/experimental/processors/reference-utils.js
packages/code-gen/src/experimental/validators/generator.d.ts
packages/code-gen/src/experimental/validators/generator.js
packages/code-gen/src/experimental/validators/javascript.js
packages/store/src/file-send.js
packages/store/src/files-jobs.js

This improves the validator performance by a lot for big anyOfs. It also simplifies the validator error objects, making them easier to understand.

feat(code-gen/experimental): add discriminant support to anyOf

---

.github/workflows/create-release.yml
.github/workflows/main-checks.yml
.github/workflows/pr-checks.yml
package-lock.json
package.json
packages/cli/package.json
packages/code-gen/package.json
packages/compas/package.json
packages/create-compas/package.json
packages/eslint-plugin/package.json
packages/server/package.json
packages/server/src/middleware/body.test.js
packages/stdlib/package.json
packages/store/package.json
test/config.js

- Dropped support for Node.js 16

chore: change minimal supported version to Node.js 18
